version: 2

jobs:
  python-3.5-client-3:
    docker:
      - image: python:3.5
      - image: redis:3
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.5-client-4:
    docker:
      - image: python:3.5
      - image: redis:4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.5-client-5:
    docker:
      - image: python:3.5
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.6-client-3:
    docker:
      - image: python:3.6
      - image: redis:3
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.6-client-4:
    docker:
      - image: python:3.6
      - image: redis:4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.6-client-5:
    docker:
      - image: python:3.6
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.7-client-3:
    docker:
      - image: python:3.7
      - image: redis:3
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.7-client-4:
    docker:
      - image: python:3.7
      - image: redis:4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.7-client-5:
    docker:
      - image: python:3.7
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.8-client-3:
    docker:
      - image: python:3.8
      - image: redis:3
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.8-client-4:
    docker:
      - image: python:3.8
      - image: redis:4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.8-client-5:
    docker:
      - image: python:3.8
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: pytest tests/client/

  python-3.5-cluster-3:
    docker:
      - image: python:3.5
      - image: grokzen/redis-cluster:3.2.11
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.5-cluster-4:
    docker:
      - image: python:3.5
      - image: grokzen/redis-cluster:4.0.9
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.5-cluster-5:
    docker:
      - image: python:3.5
      - image: grokzen/redis-cluster:5.0.4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.6-cluster-3:
    docker:
      - image: python:3.6
      - image: grokzen/redis-cluster:3.2.11
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.6-cluster-4:
    docker:
      - image: python:3.6
      - image: grokzen/redis-cluster:4.0.9
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.6-cluster-5:
    docker:
      - image: python:3.6
      - image: grokzen/redis-cluster:5.0.4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.7-cluster-3:
    docker:
      - image: python:3.7
      - image: grokzen/redis-cluster:3.2.11
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.7-cluster-4:
    docker:
      - image: python:3.7
      - image: grokzen/redis-cluster:4.0.9
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.7-cluster-5:
    docker:
      - image: python:3.7
      - image: grokzen/redis-cluster:5.0.4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.8-cluster-3:
    docker:
      - image: python:3.8
      - image: grokzen/redis-cluster:3.2.11
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.8-cluster-4:
    docker:
      - image: python:3.8
      - image: grokzen/redis-cluster:4.0.9
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.8-cluster-5:
    docker:
      - image: python:3.8
      - image: grokzen/redis-cluster:5.0.4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.5-client-3-hiredis:
    docker:
      - image: python:3.5
      - image: redis:3
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.5-client-4-hiredis:
    docker:
      - image: python:3.5
      - image: redis:4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.5-client-5-hiredis:
    docker:
      - image: python:3.5
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.6-client-3-hiredis:
    docker:
      - image: python:3.6
      - image: redis:3
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.6-client-4-hiredis:
    docker:
      - image: python:3.6
      - image: redis:4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.6-client-5-hiredis:
    docker:
      - image: python:3.6
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.7-client-3-hiredis:
    docker:
      - image: python:3.7
      - image: redis:3
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.7-client-4-hiredis:
    docker:
      - image: python:3.7
      - image: redis:4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.7-client-5-hiredis:
    docker:
      - image: python:3.7
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.8-client-3-hiredis:
    docker:
      - image: python:3.8
      - image: redis:3
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.8-client-4-hiredis:
    docker:
      - image: python:3.8
      - image: redis:4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.8-client-5-hiredis:
    docker:
      - image: python:3.8
      - image: redis:5.0
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: pytest tests/client/

  python-3.5-cluster-3-hiredis:
    docker:
      - image: python:3.5
      - image: grokzen/redis-cluster:3.2.11
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.5-cluster-4-hiredis:
    docker:
      - image: python:3.5
      - image: grokzen/redis-cluster:4.0.9
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.5-cluster-5-hiredis:
    docker:
      - image: python:3.5
      - image: grokzen/redis-cluster:5.0.4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.6-cluster-3-hiredis:
    docker:
      - image: python:3.6
      - image: grokzen/redis-cluster:3.2.11
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.6-cluster-4-hiredis:
    docker:
      - image: python:3.6
      - image: grokzen/redis-cluster:4.0.9
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.6-cluster-5-hiredis:
    docker:
      - image: python:3.6
      - image: grokzen/redis-cluster:5.0.4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.7-cluster-3-hiredis:
    docker:
      - image: python:3.7
      - image: grokzen/redis-cluster:3.2.11
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.7-cluster-4-hiredis:
    docker:
      - image: python:3.7
      - image: grokzen/redis-cluster:4.0.9
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.7-cluster-5-hiredis:
    docker:
      - image: python:3.7
      - image: grokzen/redis-cluster:5.0.4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.8-cluster-3-hiredis:
    docker:
      - image: python:3.8
      - image: grokzen/redis-cluster:3.2.11
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.8-cluster-4-hiredis:
    docker:
      - image: python:3.8
      - image: grokzen/redis-cluster:4.0.9
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

  python-3.8-cluster-5-hiredis:
    docker:
      - image: python:3.8
      - image: grokzen/redis-cluster:5.0.4
    steps:
      - checkout
      - run: python -m pip install -r test_requirements.txt
      - run: python -m pip install hiredis
      - run: sleep 10  # give the cluster some init time
      - run: pytest tests/cluster/

workflows:
  version: 2
  run-jobs:
    jobs:
      - python-3.5-client-3
      - python-3.5-client-4
      - python-3.5-client-5

      - python-3.6-client-3
      - python-3.6-client-4
      - python-3.6-client-5

      - python-3.7-client-3
      - python-3.7-client-4
      - python-3.7-client-5

      - python-3.8-client-3
      - python-3.8-client-4
      - python-3.8-client-5

      - python-3.5-cluster-3
      - python-3.5-cluster-4
      - python-3.5-cluster-5

      - python-3.6-cluster-3
      - python-3.6-cluster-4
      - python-3.6-cluster-5

      - python-3.7-cluster-3
      - python-3.7-cluster-4
      - python-3.7-cluster-5

      - python-3.8-cluster-3
      - python-3.8-cluster-4
      - python-3.8-cluster-5

      - python-3.5-client-3-hiredis
      - python-3.5-client-4-hiredis
      - python-3.5-client-5-hiredis

      - python-3.6-client-3-hiredis
      - python-3.6-client-4-hiredis
      - python-3.6-client-5-hiredis

      - python-3.7-client-3-hiredis
      - python-3.7-client-4-hiredis
      - python-3.7-client-5-hiredis

      - python-3.8-client-3-hiredis
      - python-3.8-client-4-hiredis
      - python-3.8-client-5-hiredis

      - python-3.5-cluster-3-hiredis
      - python-3.5-cluster-4-hiredis
      - python-3.5-cluster-5-hiredis

      - python-3.6-cluster-3-hiredis
      - python-3.6-cluster-4-hiredis
      - python-3.6-cluster-5-hiredis

      - python-3.7-cluster-3-hiredis
      - python-3.7-cluster-4-hiredis
      - python-3.7-cluster-5-hiredis

      - python-3.8-cluster-3-hiredis
      - python-3.8-cluster-4-hiredis
      - python-3.8-cluster-5-hiredis
