name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.7, 3.8, 3.9, "3.10"]
        service_version:
          - REDIS_VERSION=5.0.14 REDIS_SSL_VERSION=6.2.6
          - REDIS_VERSION=6.0.16 REDIS_SSL_VERSION=6.0.16
          - REDIS_VERSION=6.2.6 REDIS_SSL_VERSION=6.2.6
        parser: [hiredis, python]
        uvloop: ["False"]
        include:
          - python-version: 3.9
            service_version: "REDIS_VERSION=latest REDIS_SSL_VERSION=latest"
            parser: hiredis
            uvloop: "True"
          - python-version: "3.10"
            service_version: "REDIS_VERSION=latest REDIS_SSL_VERSION=latest"
            parser: hiredis
            uvloop: "True"
    steps:
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/**') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements/test.txt
    - name: Install Hiredis
      if: ${{ matrix.parser == 'hiredis' }}
      run:
        pip install hiredis
    - name: Tests
      env:
        COREDIS_UVLOOP: "{{matrix.uvloop}}"
      run: |
        eval "export ${{ matrix.service_version }}"
        pytest --cov-report=xml --cov-branch
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
